#!/usr/bin/env python3
"""Generate paper-ready TikZ figures from the machine-readable corpus.

Currently emits one figure:

    generated/figures/residual_heatmap.tikz

a system-by-residual coverage matrix (rows = systems ordered by year,
columns = residual capability families ordered by how many systems attack
them) with a per-residual bar summary and an evidence-level legend. The
figure is pure TikZ (no pgfplots / matrix library) so it compiles inside the
survey with only the packages the paper already loads.

Run:

    python3 scripts/export_figures.py

Every coordinate and count is derived from data/systems.json and
data/capability_families.json, so the figure is reproducible from source.
"""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
FIGURES = ROOT / "generated" / "figures"

# Short, typeset-friendly column labels for the residual families.
SHORT_LABEL = {
    "action_semantics": "Action semantics",
    "planning_utility": "Planning utility",
    "state_persistence": "State persistence",
    "sim_to_real_transfer": "Sim-to-real",
    "spatial_consistency": "Spatial consistency",
    "physical_law_extrapolation": "Physical law",
    "governance_readiness": "Governance",
    "uncertainty_calibration": "Uncertainty",
    "counterfactual_reasoning": "Counterfactual",
    "social_physical_coupling": "Social-physical",
}

# Geometry (in cm); the whole picture is rescaled to \linewidth on input.
CW = 1.04          # column width
CH = 0.40          # row height
L = 5.00           # width reserved for row labels
INSET = 0.085      # gutter inside a covered tile
DOT_X = -L + 0.14  # x of the evidence-level dot
YEAR_X = -L + 0.95  # right edge of the year stamp
NAME_X = -L + 1.05  # left edge of the system name
HEADER_Y = 0.12    # baseline for rotated column headers
BAR_H = 1.30       # height of the tallest summary bar
BAR_GAP = 1.65     # vertical gap between grid bottom and bar baseline


def load(name: str) -> list[dict[str, Any]]:
    with (DATA / name).open("r", encoding="utf-8") as f:
        return json.load(f)


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def f(value: float) -> str:
    return f"{value:.3f}"


def evidence_color(level: str) -> str:
    if level in ("official_open", "unofficial_open"):
        return "hmGreen"
    if level == "official_partial":
        return "hmOrange"
    return "hmRed"


def tex_name(text: str) -> str:
    # System names in the corpus contain only hyphens, dots and digits;
    # guard the few TeX-active characters just in case the data grows.
    out = []
    specials = {"&": "\\&", "%": "\\%", "_": "\\_", "#": "\\#", "$": "\\$"}
    for ch in str(text):
        out.append(specials.get(ch, ch))
    return "".join(out)


def build(systems: list[dict[str, Any]], families: list[dict[str, Any]]) -> str:
    counts = Counter()
    for item in systems:
        for res in item.get("residuals", []):
            counts[res] += 1

    family_ids = [fam["id"] for fam in families]
    order = sorted(family_ids, key=lambda i: (-counts.get(i, 0), family_ids.index(i)))
    col_index = {rid: c for c, rid in enumerate(order)}
    max_count = max((counts.get(i, 0) for i in order), default=1) or 1

    rows = sorted(systems, key=lambda x: (x["year"], x["name"]))
    n_rows = len(rows)
    n_cols = len(order)

    grid_w = n_cols * CW
    grid_h = n_rows * CH
    bar_base = -grid_h - BAR_GAP
    region_y = bar_base - 0.46

    # Column groups that carry the paper's headline reading.
    well_covered = set(order[:2])           # two densest residuals
    frontier = set(order[-3:])              # three sparsest residuals

    out: list[str] = [
        "% Auto-generated by scripts/export_figures.py -- DO NOT EDIT BY HAND.",
        "% Regenerate: python3 scripts/export_figures.py",
        "% Source data: data/systems.json, data/capability_families.json",
        "\\resizebox{0.96\\linewidth}{!}{%",
        "\\begin{tikzpicture}[x=1cm,y=1cm]",
        "  \\definecolor{hmInk}{RGB}{45,48,56}",
        "  \\definecolor{hmBlue}{RGB}{62,112,176}",
        "  \\definecolor{hmGreen}{RGB}{60,145,112}",
        "  \\definecolor{hmOrange}{RGB}{218,137,56}",
        "  \\definecolor{hmRed}{RGB}{172,60,74}",
    ]

    # 1. Region bands behind the grid.
    well_x1 = len(order[:2]) * CW
    out.append("  % region bands")
    out.append("  \\fill[hmGreen!8] (0," + f(0.0) + ") rectangle (" + f(well_x1) + "," + f(-grid_h) + ");")
    front_x0 = (n_cols - 3) * CW
    out.append("  \\fill[hmRed!8] (" + f(front_x0) + ",0) rectangle (" + f(grid_w) + "," + f(-grid_h) + ");")

    # 2. Faint per-row guides.
    out.append("  % row guides")
    for r in range(1, n_rows):
        y = -r * CH
        out.append("  \\draw[hmInk!7,line width=0.15pt] (0," + f(y) + ") -- (" + f(grid_w) + "," + f(y) + ");")

    # 3. Covered tiles.
    out.append("  % covered cells")
    for r, item in enumerate(rows):
        y_top = -r * CH
        y_bot = -(r + 1) * CH
        for res in item.get("residuals", []):
            c = col_index.get(res)
            if c is None:
                continue
            x0 = c * CW
            x1 = (c + 1) * CW
            out.append(
                "  \\fill[hmBlue,rounded corners=0.5pt] ("
                + f(x0 + INSET) + "," + f(y_top - INSET) + ") rectangle ("
                + f(x1 - INSET) + "," + f(y_bot + INSET) + ");"
            )

    # 4. Light column separators.
    out.append("  % column separators")
    for c in range(1, n_cols):
        x = c * CW
        out.append("  \\draw[hmInk!9,line width=0.15pt] (" + f(x) + ",0) -- (" + f(x) + "," + f(-grid_h) + ");")

    # 5. Year-group separators across the label band and the grid.
    out.append("  % year-group separators")
    for r in range(1, n_rows):
        if rows[r]["year"] != rows[r - 1]["year"]:
            y = -r * CH
            out.append("  \\draw[hmInk!28,line width=0.45pt] (" + f(-L) + "," + f(y) + ") -- (" + f(grid_w) + "," + f(y) + ");")

    # 6. Grid border.
    out.append("  \\draw[hmInk!30,line width=0.5pt] (0,0) rectangle (" + f(grid_w) + "," + f(-grid_h) + ");")

    # 7. Rotated column headers.
    out.append("  % column headers")
    for c, rid in enumerate(order):
        xc = (c + 0.5) * CW
        label = SHORT_LABEL.get(rid, rid)
        out.append(
            "  \\node[rotate=45,anchor=west,font=\\scriptsize,text=hmInk] at ("
            + f(xc) + "," + f(HEADER_Y) + ") {" + label + "};"
        )

    # 8. Row labels and evidence dots.
    out.append("  % row labels + evidence dots")
    for r, item in enumerate(rows):
        yc = -(r + 0.5) * CH
        color = evidence_color(item.get("evidence_level", "closed_reference"))
        out.append("  \\fill[" + color + "] (" + f(DOT_X) + "," + f(yc) + ") circle (0.052);")
        out.append(
            "  \\node[anchor=east,font=\\scriptsize,text=hmInk!55] at ("
            + f(YEAR_X) + "," + f(yc) + ") {" + str(item["year"]) + "};"
        )
        out.append(
            "  \\node[anchor=west,font=\\scriptsize,text=hmInk] at ("
            + f(NAME_X) + "," + f(yc) + ") {" + tex_name(item["name"]) + "};"
        )

    # 9. Per-residual summary bars.
    out.append("  % per-residual summary bars")
    out.append("  \\draw[hmInk!35,line width=0.4pt] (0," + f(bar_base) + ") -- (" + f(grid_w) + "," + f(bar_base) + ");")
    out.append(
        "  \\node[anchor=east,align=right,font=\\scriptsize,text=hmInk] at ("
        + f(-0.18) + "," + f(bar_base + BAR_H * 0.5) + ") {Systems per\\\\residual};"
    )
    for c, rid in enumerate(order):
        n = counts.get(rid, 0)
        xc = (c + 0.5) * CW
        x0 = c * CW + 0.14
        x1 = (c + 1) * CW - 0.14
        top = bar_base + (n / max_count) * BAR_H
        if rid in frontier:
            bar_color = "hmRed"
        elif rid in well_covered:
            bar_color = "hmGreen"
        else:
            bar_color = "hmBlue"
        if n > 0:
            out.append(
                "  \\fill[" + bar_color + ",rounded corners=0.4pt] ("
                + f(x0) + "," + f(bar_base) + ") rectangle (" + f(x1) + "," + f(top) + ");"
            )
        out.append(
            "  \\node[anchor=south,font=\\scriptsize\\bfseries,text=" + bar_color + "] at ("
            + f(xc) + "," + f(top + 0.04) + ") {" + str(n) + "};"
        )

    # 10. Region captions under the bars.
    out.append("  % region captions")
    out.append(
        "  \\node[anchor=north,font=\\scriptsize\\itshape,text=hmGreen!60!black] at ("
        + f(well_x1 * 0.5) + "," + f(region_y) + ") {Heavily built};"
    )
    out.append(
        "  \\node[anchor=north,font=\\scriptsize\\itshape,text=hmRed] at ("
        + f((front_x0 + grid_w) * 0.5) + "," + f(region_y) + ") {Under-built frontier};"
    )

    # 11. Evidence-level legend in the empty top-left corner.
    out.append("  % evidence-level legend")
    legend_x = -L
    out.append(
        "  \\node[anchor=west,font=\\scriptsize\\bfseries,text=hmInk] at ("
        + f(legend_x) + ",0.86) {Evidence level};"
    )
    legend_items = [("hmGreen", "open code/weights"), ("hmOrange", "partial"), ("hmRed", "closed reference")]
    ly = 0.60
    for color, text in legend_items:
        out.append("  \\fill[" + color + "] (" + f(legend_x + 0.10) + "," + f(ly) + ") circle (0.052);")
        out.append(
            "  \\node[anchor=west,font=\\scriptsize,text=hmInk] at ("
            + f(legend_x + 0.24) + "," + f(ly) + ") {" + text + "};"
        )
        ly -= 0.24

    out.append("\\end{tikzpicture}}")
    return "\n".join(out) + "\n"


def main() -> int:
    systems = load("systems.json")
    families = load("capability_families.json")
    figure = build(systems, families)
    target = FIGURES / "residual_heatmap.tikz"
    write(target, figure)
    print(f"OK: wrote {target.relative_to(ROOT)} ({len(systems)} systems, {len(families)} residual families).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
